# $schema=https://www.schemastore.org/github-action.json
name: "Build single melange package"
description: "Builds a single package using melange"

inputs:
  melange-config-file:
    description: "Path to melange config file"
    default: "melange.yaml"
  build-arch:
    description: "The architecture(s) to build the package for (comma separated)"
    default: "x86_64"
  cache-dir:
    description: "The directory to store build cache files in"
    default: "./.cache/"
  out-dir:
    description: "The directory to output built packages into"
    default: "./packages/"
  signing-key:
    description: "The private key used to sign the built packages (PEM format)"
  signing-key-name:
    description: "The name of the key used to sign the built packages (not including the .rsa/.rsa.pub suffix)"
  package-namespace:
    description: "namespace to use in package URLs in SBOM (eg wolfi, alpine) (default 'unknown')"
  generate-index:
    description: "generate APKINDEX.tar.gz"
    default: "true"
  generate-provenance:
    description: "generate SLSA provenance for builds (included in a separate .attest.tar.gz file next to the APK)"
    default: "true"

runs:
  using: "composite"

  steps:
    - name: Build package
      shell: bash
      env:
        CACHE_DIR: "${{ inputs.cache-dir }}"
        OUT_DIR: "${{ inputs.out-dir }}"
        ARCH:  "${{ inputs.build-arch }}"
        SIGNING_KEY: "${{ inputs.signing-key }}"
        SIGNING_KEY_NAME: "${{ inputs.signing-key-name }}"
        MELANGE_CONFIG_FILE: "${{ inputs.melange-config-file }}"
        PACKAGE_NAMESPACE: "${{ inputs.package-namespace }}"
        GENERATE_INDEX: "${{ inputs.generate-index }}"
        GENERATE_PROVENANCE: "${{ inputs.generate-provenance }}"
      run: |
        set -euo pipefail

        chmod +x "${GITHUB_ACTION_PATH}/build-package.sh"
        "${GITHUB_ACTION_PATH}/build-package.sh"
